train:
  seq_length: 520
  epochs: 30
  total_steps: 100000
  batch_size: 8
  checkpoint_interval: 10000
  eval_interval: 50
  pipeline: "PromptPipeline"
  trainer: "CustomPPOTrainer"
  tracker: wandb
  project_name: rlhf
  entity_name: open-assistant

model:
  model_path:
  num_layers_unfrozen: -1

tokenizer:
  tokenizer_path:
  truncation_side: "right"
  padding_side: "left"

optimizer:
  name: "adamw"
  kwargs:
    lr: 2.0e-6
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-3

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 100000 # train.total_steps
    eta_min: 1.0e-4

method:
  name: "ppoconfig"
  num_rollouts: 256
  chunk_size: 8
  ppo_epochs: 4
  init_kl_coef: 0.1
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 100
    top_k: 0
    top_p: 0.7
    do_sample: True
    temperature: 0.5
