train:
  seq_length: 520
  epochs: 12
  total_steps: 10000
  batch_size: 18
  checkpoint_interval: 1000
  eval_interval: 500
  pipeline: "PromptPipeline"
  trainer: "PPOTrainer"
  tracker: wandb
  project_name: rlhf
  entity_name: open-assistant

model:
  model_path: "EleutherAI/pythia-1b-deduped-base-finetuned/checkpoint-500"
  num_layers_unfrozen: -1

tokenizer:
  tokenizer_path: "EleutherAI/pythia-1b-deduped-base-finetuned/checkpoint-500"
  truncation_side: "right"

optimizer:
  name: "adamw"
  kwargs:
    lr: 2.0e-6
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 1.0e-3

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 10000 # train.total_steps
    eta_min: 1.0e-4

method:
  name: "ppoconfig"
  num_rollouts: 384
  chunk_size: 8
  ppo_epochs: 4
  init_kl_coef: 0.05
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 40
    top_k: 0
    top_p: 1.0
    do_sample: True
